# Change these first
owner: mendoanjoe # Your GitHub organization or username, where this repository lives
repo: watcher # The name of this repository

sites:
  - name: Telkomsel PAS
    url: https://pastiadasolusi.com
  - name: Telkomsel PAS REST
    url: https://api.pastiadasolusi.com

status-website:
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: IS UP
  introTitle: "powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
